USE [master]
GO

/****** Object:  Database [TestCrud]    Script Date: 23/05/2018 18:59:28 ******/
DROP DATABASE [TestCrud]
GO

/****** Object:  Database [TestCrud]    Script Date: 23/05/2018 18:59:28 ******/
CREATE DATABASE [TestCrud]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestCrud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestCrud.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestCrud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TestCrud_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TestCrud] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestCrud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestCrud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestCrud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestCrud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestCrud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestCrud] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestCrud] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestCrud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestCrud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestCrud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestCrud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestCrud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestCrud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestCrud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestCrud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestCrud] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestCrud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestCrud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestCrud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestCrud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestCrud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestCrud] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestCrud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestCrud] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestCrud] SET  MULTI_USER 
GO

ALTER DATABASE [TestCrud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestCrud] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestCrud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestCrud] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestCrud] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestCrud] SET QUERY_STORE = OFF
GO

USE [TestCrud]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TestCrud] SET  READ_WRITE 
GO


